version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: recruitment-rabbitmq
    ports:
      - "5672:5672"   # AMQP 协议端口
      - "15672:15672" # 管理界面端口
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
    networks:
      - recruitment-network

  # 可以添加其他服务，如MySQL、应用服务等

networks:
  recruitment-network:
    driver: bridge

volumes:
  rabbitmq_data: