server:
  port: 7001

spring:
  application:
    name: eureka-server

eureka:
  server:
    enable-self-preservation: false           # 关闭自我保护
    eviction-interval-timer-in-ms: 1000      # 清理无效节点的时间间隔（1秒）
    response-cache-update-interval-ms: 1000   # 刷新缓存时间间隔（1秒）
    response-cache-auto-expiration-in-seconds: 1   # 缓存过期时间（1秒）
    renewal-percent-threshold: 0.49           # 关闭自我保护的阈值
    renewal-threshold-update-interval-ms: 1000  # 更新续约阈值的间隔（1秒）
  instance:
    hostname: localhost
  client:
    register-with-eureka: false    # 不向自己注册
    fetch-registry: false          # 不从自己拉取服务列表
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

