server:
  port: 8005

spring:
  application:
    name: recruitment-service
  datasource:
    url: jdbc:mysql://localhost:3306/recruitment_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.163.com
    username: zzzyt217@163.com
    password: THULqamnbVa3RWL4
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          socketFactory:
            port: 25
            class: javax.net.ssl.SSLSocketFactory
          timeout: 25000
          connectiontimeout: 25000
        transport:
          protocol: smtp
        debug: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

logging:
  level:
    com.test.Mapper: DEBUG
    org.springframework.mail: DEBUG
    javax.mail: DEBUG
    com.sun.mail: DEBUG
    
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl