server:
  port: 8003

spring:
  application:
    name: company-service
  datasource:
    url: jdbc:mysql://localhost:3306/company1_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
