server:
  port: 8006

spring:
  application:
    name: analytics-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: false
    instance-id: localhost:${spring.application.name}:${server.port}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full